baseURL = "https://johnmccrmck.com/"
languageCode = "en-us"
title = "screenslav3r"
theme="archie"
copyright = "© screenslav3r"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=10 # articles per page

[params]
	mode="dark" # color-mode → light,dark or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "CyberSecurtiy Walkthrough, How-Tos, and Articles"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/johnmccrmck"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/athulcajay/"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/athul/"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://gitlab.com/athul/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4